default_language_version:
    python: python3.11
repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.1.3
      hooks:
        - id: ruff
        - id: ruff-format
          args: [--check]
