# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Release a package

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

permissions:
  contents: write
  pull-requests: read

jobs:
  build:
    name: Build sr0wx on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r dev.txt
    - name: Build PyInstaller bundle
      run: |
        pyinstaller ./sr0wx.spec -y
    - name: Archive assets with executable
      if: runner.os == 'Linux'
      run: |
        mv dist/sr0wx .
        tar czf "sr0wx_linux_amd64.tar.gz" sr0wx assets/ config.toml

    - name: Archive assets with executable
      if: runner.os == 'Windows'
      run: |
        Move-Item dist/sr0wx.exe .
        $compress = @{
          Path = "sr0wx.exe", "assets", "config.toml"
          CompressionLevel = "Optimal"
          DestinationPath = "sr0wx_win64.zip"
        }
        Compress-Archive @compress

    - name: Upload Builds
      uses: actions/upload-artifact@v3
      with:
        name: built-binary
        path: |
          ./*.tar.gz

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: built-binary

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "*.tar.gz,*.zip"
          generateReleaseNotes: true
